name: dentality
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.2
  equatable: ^2.0.5
  firebase_auth: ^4.15.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.6
  flutter_riverpod: ^2.4.5
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Black.ttf
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo2-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Exo2-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Exo2-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Exo2-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Exo2-ExtraLightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Exo2-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Exo2-Italic.ttf
          style: italic
        - asset: assets/fonts/Exo2-Light.ttf
          weight: 300
