// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbpYCj_E_MP3_Hqr9xzgi_T8iZTPY8oJk',
    appId: '1:296560098854:web:bd98dcc7e1073340c9f0e7',
    messagingSenderId: '296560098854',
    projectId: 'i-dentify-fce91',
    authDomain: 'i-dentify-fce91.firebaseapp.com',
    storageBucket: 'i-dentify-fce91.appspot.com',
    measurementId: 'G-TJSJCR4R1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpSKsoI0aBRqX-IAPZfsfWpcTHxdavdRI',
    appId: '1:296560098854:android:0bcb6c852a2b3578c9f0e7',
    messagingSenderId: '296560098854',
    projectId: 'i-dentify-fce91',
    storageBucket: 'i-dentify-fce91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8LdabIT-yEtTAwnUliNoDFS2mfTKjsSY',
    appId: '1:296560098854:ios:d4415715f01ef35ec9f0e7',
    messagingSenderId: '296560098854',
    projectId: 'i-dentify-fce91',
    storageBucket: 'i-dentify-fce91.appspot.com',
    iosBundleId: 'com.example.dentality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8LdabIT-yEtTAwnUliNoDFS2mfTKjsSY',
    appId: '1:296560098854:ios:8a3a456a29ce28bec9f0e7',
    messagingSenderId: '296560098854',
    projectId: 'i-dentify-fce91',
    storageBucket: 'i-dentify-fce91.appspot.com',
    iosBundleId: 'com.example.dentality.RunnerTests',
  );
}
